### PR TITLE
Login and signup forms

### PR DESCRIPTION
**Pull request by ejena-black**
I'm done with the form, but possible refactor from alfred. @highb33kay review and merge

### CODE REVIEW

**Comment by highb33kay** [comment]
@ejena-black please review

**Comment by ejena-black** [comment]
all good

**Review by ejena-black — COMMENTED** [review]
done

**Comment by ejena-black** [comment]
I've reviewed please merge @highb33kay

**Review by highb33kay — APPROVED** [review]

**Pull request merged**
